name: CICD on Github Action

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

    #  - name: Login to DockerHub
    #    uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKER_USER }}
    #    password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v1
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: jayvirrathi/nodejs:v1    

      - name: Set output image tag
        id: image_tag
        run: echo "::set-output name=image_tag;jayvirrathi/nodejs:v1" 

  deploy:
    needs: build
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        uses: steebchen/kubectl-setup@v1
        with:
          version: 'latest'

      - name: Update image tag in deployment file
        run: sed -i "s|jayvirrathi/nodejs:v1|${{ needs.build.outputs.image_tag }}|g" deployment/deployment.yaml

      - name: Apply deployment file
        run: kubectl apply -f deployment/deployment.yaml
